# Generated by Django 4.1.6 on 2023-03-05 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items_list", "0008_remove_shoppinglist_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 5, 13, 2, 42, 247147)
            ),
        ),
    ]
