# Generated by Django 4.1.6 on 2023-03-05 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items_list", "0009_shoppinglist_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 5, 13, 6, 1, 490579)
            ),
        ),
    ]
