# Generated by Django 4.1.6 on 2023-03-11 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items_list", "0010_shoppinglist_is_public_alter_shoppinglist_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="no_sugar",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 11, 9, 19, 16, 68114)
            ),
        ),
    ]
